# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hacklist' do
  use_frameworks!

  # Pods for Hacklist
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'HacklistTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
